INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Mr. Chocolate" 20, "M", "dark brown", "calm", 0)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Rowdy" 10, "M", "black", "intense", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Tabitha", 6, "F", "dark brown", "Nice", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Sergeant Brown", 19, "M", "Green", "Slimy", 0)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Melissa", 13, "F", "dark brown", "goofy", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Grinch", 2, "M", "Black", "Grinchy", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Wendy",28, "F", "Brown with a White Streak", "Funny", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Null", 65, "M", "Blackest Black", "Angry when Provoked", 1)
