INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Mr. Chocolate" 22, "M", "Brown", "Fiesty", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Rowdy" 37, "M", "Black", "Cool as a Cucumber", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Tabitha", 19, "Black and Brown", "F", "Sweet", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Sergeant Brown", 87, "M", "Dark Brown", "Alpha", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Melissa", 46, "F", "White", "Stable", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Grinch", 100, "M", "Gray", "Angry Old Man", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Wendy",28, "F", "Brown with a White Streak", "Funny", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Null", 65, "M", "Blackest Black", "Angry when Provoked", 1)
